/*
  # Add recurrence fields to medications table

  1. Changes
    - Add recurrence_type column (none, daily, weekly, custom)
    - Add recurrence_interval column for custom intervals
    - Add recurrence_end_date column for when recurrence stops
    - Add recurrence column (JSONB) for rich recurrence rules (auto-populated by trigger)

  2. Details
    - frequency field stores human-readable frequency (e.g., "1x par jour", "Tous les 8h")
    - recurrence_type is simplified type for UI
    - recurrence_interval is number of days/weeks/months between occurrences
    - recurrence JSONB is auto-generated by trigger with full rule details

  3. Security
    - RLS policies already enabled, new columns accessible to medication owners
*/

DO $$
BEGIN
  -- Add recurrence_type column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'medications' AND column_name = 'recurrence_type'
  ) THEN
    ALTER TABLE medications ADD COLUMN recurrence_type text DEFAULT 'none';
  END IF;

  -- Add recurrence_interval column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'medications' AND column_name = 'recurrence_interval'
  ) THEN
    ALTER TABLE medications ADD COLUMN recurrence_interval integer;
  END IF;

  -- Add recurrence_end_date column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'medications' AND column_name = 'recurrence_end_date'
  ) THEN
    ALTER TABLE medications ADD COLUMN recurrence_end_date date;
  END IF;

  -- Add recurrence column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'medications' AND column_name = 'recurrence'
  ) THEN
    ALTER TABLE medications ADD COLUMN recurrence jsonb;
  END IF;
END $$;

-- Create or replace trigger function to generate recurrence rules
CREATE OR REPLACE FUNCTION generate_medication_recurrence()
RETURNS TRIGGER AS $$
BEGIN
  -- Only process if recurrence_type is not 'none'
  IF NEW.recurrence_type IS NOT NULL AND NEW.recurrence_type != 'none' THEN
    NEW.recurrence := jsonb_build_object(
      'freq', CASE
        WHEN NEW.recurrence_type = 'daily' THEN 'daily'
        WHEN NEW.recurrence_type = 'weekly' THEN 'weekly'
        ELSE 'daily'
      END,
      'interval', COALESCE(NEW.recurrence_interval, 1),
      'end_date', NEW.recurrence_end_date
    );
  ELSE
    NEW.recurrence := NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if it exists and recreate
DROP TRIGGER IF EXISTS medications_recurrence_trigger ON medications;

CREATE TRIGGER medications_recurrence_trigger
  BEFORE INSERT OR UPDATE ON medications
  FOR EACH ROW
  EXECUTE FUNCTION generate_medication_recurrence();
